name: Flutter CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # os: [ubuntu-latest]
        os: [macos-latest]
        api-level: [29]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.20.2'
          channel: 'beta'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: touch .env
      - run: flutter  analyze
      - run: flutter test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          profile: pixel
          arch: x86_64
          script: |
            flutter driver --target=test_driver/main.dart >> tmp.txt
            if cat tmp.txt | grep -q 'Some tests failed.'; then false; else true; fi
